### ISSUE TITLE
線画化実施時にエラーがでて入力線画が参照されない

### ISSUE THREAD

**Issue by mmmmeitei** [tori29umai0123/AI-Assistant#20]
素晴らしいアプリをありがとうございます。
6/17の全体公開時にNoteのリンクに記載のあるGoogleドライブからDLした際は画像サイズが変わってしまう以外は正しく動作していたのですが、[こちらの](https://x.com/tori29umai/status/1804295264024564001) ポストをみてGoogleドライブから落とし直して更新した所、線画化の実施時にエラーを出しながら生成を続行し、結果、入力画像が参考にされていないような出力をするようになってしまいました。
おま環の可能性はあるのですが、念の為報告しておきます。
線画化実行時のログは以下になります。
実行環境はWindows11・RTX3060TIの8GBで、AI_Assistant_lowVRAM.batから起動していました。
```
2024-06-22 21:23:09,179 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-06-22 21:23:09,181 - ControlNet - INFO - Using preprocessor: None
2024-06-22 21:23:09,181 - ControlNet - INFO - preprocessor resolution = 896
*** Error running process: E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 548, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 406, in process_unit_after_click_generate
        model_filename = global_state.get_controlnet_filename(unit.model)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\lib_controlnet\global_state.py", line 75, in get_controlnet_filename
        return controlnet_filename_dict[controlnet_name]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    KeyError: 'control-lora-canny-rank256 [ec2dbbe4]'

---
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000021581148650>, <modules.extra_networks.ExtraNetworkParams object at 0x0000021581148950>]: AttributeError
Traceback (most recent call last):
  File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\Lora\networks.py", line 56, in load_networks
    net = load_network(name, network_on_disk)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\Lora\networks.py", line 31, in load_network
    net.mtime = os.path.getmtime(network_on_disk.filename)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\Lora\networks.py", line 58, in load_networks
    errors.display(e, f"loading network {network_on_disk.filename}")
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'filename'

*** Error running process_before_every_sampling: E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
                                                         ~~~~~~~~~~~~~~~~~~~^^^
    KeyError: 0

---
To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7072.291015625
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1151.2045211791992
Moving model(s) has taken 1.06 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.79it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.79it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7071.552734375
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5887.995653152466
Moving model(s) has taken 0.92 seconds
*** Error running postprocess_batch_list: E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI_Assistant_V3\AI_Assistant\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
                                                        ~~~~~~~~~~~~~~~~~~~^^^
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.66it/s]
INFO:     127.0.0.1:63998 - "POST /sdapi/v1/img2img HTTP/1.1" 200 OK███████████████████| 20/20 [00:12<00:00,  1.79it/s]
INFO:     127.0.0.1:64000 - "POST /sdapi/v1/png-info HTTP/1.1" 200 OK
Downloaded E:\AI_Assistant_V3\AI_Assistant\output\2024-06-22_21-23-09.png to local
INFO:     127.0.0.1:63997 - "POST /api/predict HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     127.0.0.1:63997 - "POST /reset HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 64001) - "WebSocket /queue/join" [accepted]
INFO:     connection open
INFO:     ('127.0.0.1', 64002) - "WebSocket /queue/join" [accepted]
INFO:     connection open
INFO:     ('127.0.0.1', 64003) - "WebSocket /queue/join" [accepted]
INFO:     connection open
INFO:     127.0.0.1:63997 - "POST /api/predict HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     127.0.0.1:63997 - "POST /reset HTTP/1.1" 200 OK
INFO:     127.0.0.1:63997 - "POST /api/predict HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     127.0.0.1:63997 - "POST /reset HTTP/1.1" 200 OK
INFO:     127.0.0.1:63997 - "POST /api/predict HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     127.0.0.1:63997 - "POST /reset HTTP/1.1" 200 OK

```

**Comment by tori29umai0123** [comment]
ご報告ありがとうございます。
おそらくですがcontrol-lora-canny-rank256 [ec2dbbe4]'のDLが失敗してしまっているので手動でDLしなおしていただけると治るかもです

**Comment by tori29umai0123** [comment]
いえ、犯人は私でした！モデルダウンロードスクリプト（AI_Assistant_model_DL.cmd）にバグを仕込んでいました！
ご報告ありがとうございます。新しいバージョンでモデルDLしなおしてくださいませ。
https://drive.google.com/file/d/1YmS8qlmvThjn-ZMXEm2QTwOC0pPcX7Gq/view?usp=drive_link

**Comment by mmmmeitei** [comment]
新しいバージョンでDLし直した結果、正常に動作するようになりました。
素早いご対応ありがとうございました！
