### ISSUE TITLE
色見本でエラー

### ISSUE THREAD

**Issue by githabtane** [tori29umai0123/AI-Assistant#21]
File "AI_Assistant_modules\actions\color_scheme.py", line 53, in _process
UnboundLocalError: cannot access local variable 'base_pil' where it is not associated with a value
INFO:     127.0.0.1:50685 - "POST /api/predict HTTP/1.1" 500 Internal Server Error
INFO:     connection closed
INFO:     127.0.0.1:50685 - "POST /reset HTTP/1.1" 200 OK

**Comment by githabtane** [comment]
Traceback (most recent call last):
  File "gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "AI_Assistant_modules\actions\color_scheme.py", line 53, in _process
UnboundLocalError: cannot access local variable 'base_pil' where it is not associated with a value

**Comment by tori29umai0123** [comment]
修正しました。
新しいバージョンをDLしなおしてください！
https://drive.google.com/file/d/1YmS8qlmvThjn-ZMXEm2QTwOC0pPcX7Gq/view?usp=drive_link

**Comment by githabtane** [comment]
修正されました。ありがとうございます。
