### ISSUE TITLE
unable to select image: tkinter.TclError: can't invoke "canvas" command: application has been destroyed

### ISSUE THREAD

**Issue by jtydhr88** [tori29umai0123/AI-Assistant#6]
Hi,
I tried both source and bundle (from https://note.com/tori29umai/n/n7dfbff92be6a?sub_rt=share_h), neither to allow me to select image
Env:
- Windows 10.
- Python 3.10.
- 3090
- cuda 12.1

Bundle version:
1. run AI_Assistant.exe directly, and get the UI, and click 
![image](https://github.com/tori29umai0123/AI-Assistant/assets/860985/2e7156af-e7da-4b1c-91bf-9f32516c386b)
2. then the whole windows is blur, and could not select image
![image](https://github.com/tori29umai0123/AI-Assistant/assets/860985/4304b1c2-80d2-4f14-a6c6-487568b00d4f)

3. python console throws:Unhandled exception in listener callback
```
Traceback (most recent call last):
  File "pynput\_util\__init__.py", line 228, in inner
  File "pynput\_util\win32.py", line 390, in _handler
  File "pynput\mouse\_win32.py", line 212, in _handle
  File "pynput\_util\__init__.py", line 144, in inner
  File "utils\capture.py", line 33, in on_click
  File "tkinter\__init__.py", line 2763, in __init__
  File "tkinter\__init__.py", line 2647, in __init__
_tkinter.TclError: can't invoke "canvas" command: application has been destroyed
```

Source version:
1. clone and setup local python env.
2. run python AI_Assistant.py
3. get the UI, and click the button as well
4. the same error, the whole window is blur and the python throws unable to select image: tkinter.TclError: can't invoke "canvas" command: application has been destroyed

I assume I am missing something needs to be installed on my local.

**Comment by jtydhr88** [comment]
looks like I used in wrong way, close it
